<?php
/**
 * DefaultApi
 * PHP version 8.1
 *
 * @category Class
 * @package  AHRDMail\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AppService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AHRDMail\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use AHRDMail\Client\ApiException;
use AHRDMail\Client\Configuration;
use AHRDMail\Client\FormDataProcessor;
use AHRDMail\Client\HeaderSelector;
use AHRDMail\Client\ObjectSerializer;

/**
 * DefaultApi Class Doc Comment
 *
 * @category Class
 * @package  AHRDMail\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DefaultApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'checkEmailIdentityDns' => [
            'application/json',
        ],
        'createEmailIdentity' => [
            'application/json',
        ],
        'createSubtenant' => [
            'application/json',
        ],
        'deleteEmailIdentity' => [
            'application/json',
        ],
        'listCampaignMetrics' => [
            'application/json',
        ],
        'listEmailIdentities' => [
            'application/json',
        ],
        'listSubtenantMetrics' => [
            'application/json',
        ],
        'sendEmail' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation checkEmailIdentityDns
     *
     * @param  \AHRDMail\Client\Model\CheckEmailIdentityDnsRequestContent $check_email_identity_dns_request_content check_email_identity_dns_request_content (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['checkEmailIdentityDns'] to see the possible values for this operation
     *
     * @throws \AHRDMail\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \AHRDMail\Client\Model\CheckEmailIdentityDnsResponseContent|\AHRDMail\Client\Model\ValidationExceptionResponseContent
     */
    public function checkEmailIdentityDns($check_email_identity_dns_request_content, string $contentType = self::contentTypes['checkEmailIdentityDns'][0])
    {
        list($response) = $this->checkEmailIdentityDnsWithHttpInfo($check_email_identity_dns_request_content, $contentType);
        return $response;
    }

    /**
     * Operation checkEmailIdentityDnsWithHttpInfo
     *
     * @param  \AHRDMail\Client\Model\CheckEmailIdentityDnsRequestContent $check_email_identity_dns_request_content (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['checkEmailIdentityDns'] to see the possible values for this operation
     *
     * @throws \AHRDMail\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \AHRDMail\Client\Model\CheckEmailIdentityDnsResponseContent|\AHRDMail\Client\Model\ValidationExceptionResponseContent, HTTP status code, HTTP response headers (array of strings)
     */
    public function checkEmailIdentityDnsWithHttpInfo($check_email_identity_dns_request_content, string $contentType = self::contentTypes['checkEmailIdentityDns'][0])
    {
        $request = $this->checkEmailIdentityDnsRequest($check_email_identity_dns_request_content, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\AHRDMail\Client\Model\CheckEmailIdentityDnsResponseContent',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\AHRDMail\Client\Model\ValidationExceptionResponseContent',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\AHRDMail\Client\Model\CheckEmailIdentityDnsResponseContent',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AHRDMail\Client\Model\CheckEmailIdentityDnsResponseContent',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AHRDMail\Client\Model\ValidationExceptionResponseContent',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation checkEmailIdentityDnsAsync
     *
     * @param  \AHRDMail\Client\Model\CheckEmailIdentityDnsRequestContent $check_email_identity_dns_request_content (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['checkEmailIdentityDns'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function checkEmailIdentityDnsAsync($check_email_identity_dns_request_content, string $contentType = self::contentTypes['checkEmailIdentityDns'][0])
    {
        return $this->checkEmailIdentityDnsAsyncWithHttpInfo($check_email_identity_dns_request_content, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation checkEmailIdentityDnsAsyncWithHttpInfo
     *
     * @param  \AHRDMail\Client\Model\CheckEmailIdentityDnsRequestContent $check_email_identity_dns_request_content (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['checkEmailIdentityDns'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function checkEmailIdentityDnsAsyncWithHttpInfo($check_email_identity_dns_request_content, string $contentType = self::contentTypes['checkEmailIdentityDns'][0])
    {
        $returnType = '\AHRDMail\Client\Model\CheckEmailIdentityDnsResponseContent';
        $request = $this->checkEmailIdentityDnsRequest($check_email_identity_dns_request_content, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'checkEmailIdentityDns'
     *
     * @param  \AHRDMail\Client\Model\CheckEmailIdentityDnsRequestContent $check_email_identity_dns_request_content (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['checkEmailIdentityDns'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function checkEmailIdentityDnsRequest($check_email_identity_dns_request_content, string $contentType = self::contentTypes['checkEmailIdentityDns'][0])
    {

        // verify the required parameter 'check_email_identity_dns_request_content' is set
        if ($check_email_identity_dns_request_content === null || (is_array($check_email_identity_dns_request_content) && count($check_email_identity_dns_request_content) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $check_email_identity_dns_request_content when calling checkEmailIdentityDns'
            );
        }


        $resourcePath = '/email-identity/check-dns';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($check_email_identity_dns_request_content)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($check_email_identity_dns_request_content));
            } else {
                $httpBody = $check_email_identity_dns_request_content;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation createEmailIdentity
     *
     * @param  \AHRDMail\Client\Model\CreateEmailIdentityRequestContent $create_email_identity_request_content create_email_identity_request_content (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createEmailIdentity'] to see the possible values for this operation
     *
     * @throws \AHRDMail\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \AHRDMail\Client\Model\CreateEmailIdentityResponseContent|\AHRDMail\Client\Model\ValidationExceptionResponseContent
     */
    public function createEmailIdentity($create_email_identity_request_content, string $contentType = self::contentTypes['createEmailIdentity'][0])
    {
        list($response) = $this->createEmailIdentityWithHttpInfo($create_email_identity_request_content, $contentType);
        return $response;
    }

    /**
     * Operation createEmailIdentityWithHttpInfo
     *
     * @param  \AHRDMail\Client\Model\CreateEmailIdentityRequestContent $create_email_identity_request_content (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createEmailIdentity'] to see the possible values for this operation
     *
     * @throws \AHRDMail\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \AHRDMail\Client\Model\CreateEmailIdentityResponseContent|\AHRDMail\Client\Model\ValidationExceptionResponseContent, HTTP status code, HTTP response headers (array of strings)
     */
    public function createEmailIdentityWithHttpInfo($create_email_identity_request_content, string $contentType = self::contentTypes['createEmailIdentity'][0])
    {
        $request = $this->createEmailIdentityRequest($create_email_identity_request_content, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\AHRDMail\Client\Model\CreateEmailIdentityResponseContent',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\AHRDMail\Client\Model\ValidationExceptionResponseContent',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\AHRDMail\Client\Model\CreateEmailIdentityResponseContent',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AHRDMail\Client\Model\CreateEmailIdentityResponseContent',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AHRDMail\Client\Model\ValidationExceptionResponseContent',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation createEmailIdentityAsync
     *
     * @param  \AHRDMail\Client\Model\CreateEmailIdentityRequestContent $create_email_identity_request_content (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createEmailIdentity'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createEmailIdentityAsync($create_email_identity_request_content, string $contentType = self::contentTypes['createEmailIdentity'][0])
    {
        return $this->createEmailIdentityAsyncWithHttpInfo($create_email_identity_request_content, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createEmailIdentityAsyncWithHttpInfo
     *
     * @param  \AHRDMail\Client\Model\CreateEmailIdentityRequestContent $create_email_identity_request_content (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createEmailIdentity'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createEmailIdentityAsyncWithHttpInfo($create_email_identity_request_content, string $contentType = self::contentTypes['createEmailIdentity'][0])
    {
        $returnType = '\AHRDMail\Client\Model\CreateEmailIdentityResponseContent';
        $request = $this->createEmailIdentityRequest($create_email_identity_request_content, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createEmailIdentity'
     *
     * @param  \AHRDMail\Client\Model\CreateEmailIdentityRequestContent $create_email_identity_request_content (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createEmailIdentity'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createEmailIdentityRequest($create_email_identity_request_content, string $contentType = self::contentTypes['createEmailIdentity'][0])
    {

        // verify the required parameter 'create_email_identity_request_content' is set
        if ($create_email_identity_request_content === null || (is_array($create_email_identity_request_content) && count($create_email_identity_request_content) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_email_identity_request_content when calling createEmailIdentity'
            );
        }


        $resourcePath = '/email-identities';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_email_identity_request_content)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_email_identity_request_content));
            } else {
                $httpBody = $create_email_identity_request_content;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation createSubtenant
     *
     * @param  \AHRDMail\Client\Model\CreateSubtenantRequestContent $create_subtenant_request_content create_subtenant_request_content (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createSubtenant'] to see the possible values for this operation
     *
     * @throws \AHRDMail\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \AHRDMail\Client\Model\CreateSubtenantResponseContent|\AHRDMail\Client\Model\ValidationExceptionResponseContent
     */
    public function createSubtenant($create_subtenant_request_content, string $contentType = self::contentTypes['createSubtenant'][0])
    {
        list($response) = $this->createSubtenantWithHttpInfo($create_subtenant_request_content, $contentType);
        return $response;
    }

    /**
     * Operation createSubtenantWithHttpInfo
     *
     * @param  \AHRDMail\Client\Model\CreateSubtenantRequestContent $create_subtenant_request_content (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createSubtenant'] to see the possible values for this operation
     *
     * @throws \AHRDMail\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \AHRDMail\Client\Model\CreateSubtenantResponseContent|\AHRDMail\Client\Model\ValidationExceptionResponseContent, HTTP status code, HTTP response headers (array of strings)
     */
    public function createSubtenantWithHttpInfo($create_subtenant_request_content, string $contentType = self::contentTypes['createSubtenant'][0])
    {
        $request = $this->createSubtenantRequest($create_subtenant_request_content, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\AHRDMail\Client\Model\CreateSubtenantResponseContent',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\AHRDMail\Client\Model\ValidationExceptionResponseContent',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\AHRDMail\Client\Model\CreateSubtenantResponseContent',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AHRDMail\Client\Model\CreateSubtenantResponseContent',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AHRDMail\Client\Model\ValidationExceptionResponseContent',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation createSubtenantAsync
     *
     * @param  \AHRDMail\Client\Model\CreateSubtenantRequestContent $create_subtenant_request_content (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createSubtenant'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createSubtenantAsync($create_subtenant_request_content, string $contentType = self::contentTypes['createSubtenant'][0])
    {
        return $this->createSubtenantAsyncWithHttpInfo($create_subtenant_request_content, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createSubtenantAsyncWithHttpInfo
     *
     * @param  \AHRDMail\Client\Model\CreateSubtenantRequestContent $create_subtenant_request_content (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createSubtenant'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createSubtenantAsyncWithHttpInfo($create_subtenant_request_content, string $contentType = self::contentTypes['createSubtenant'][0])
    {
        $returnType = '\AHRDMail\Client\Model\CreateSubtenantResponseContent';
        $request = $this->createSubtenantRequest($create_subtenant_request_content, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createSubtenant'
     *
     * @param  \AHRDMail\Client\Model\CreateSubtenantRequestContent $create_subtenant_request_content (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createSubtenant'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createSubtenantRequest($create_subtenant_request_content, string $contentType = self::contentTypes['createSubtenant'][0])
    {

        // verify the required parameter 'create_subtenant_request_content' is set
        if ($create_subtenant_request_content === null || (is_array($create_subtenant_request_content) && count($create_subtenant_request_content) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_subtenant_request_content when calling createSubtenant'
            );
        }


        $resourcePath = '/subtenants';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_subtenant_request_content)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_subtenant_request_content));
            } else {
                $httpBody = $create_subtenant_request_content;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteEmailIdentity
     *
     * @param  string $id id (required)
     * @param  string|null $subtenant_id subtenant_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteEmailIdentity'] to see the possible values for this operation
     *
     * @throws \AHRDMail\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \AHRDMail\Client\Model\DeleteEmailIdentityResponseContent|\AHRDMail\Client\Model\ValidationExceptionResponseContent
     */
    public function deleteEmailIdentity($id, $subtenant_id = null, string $contentType = self::contentTypes['deleteEmailIdentity'][0])
    {
        list($response) = $this->deleteEmailIdentityWithHttpInfo($id, $subtenant_id, $contentType);
        return $response;
    }

    /**
     * Operation deleteEmailIdentityWithHttpInfo
     *
     * @param  string $id (required)
     * @param  string|null $subtenant_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteEmailIdentity'] to see the possible values for this operation
     *
     * @throws \AHRDMail\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \AHRDMail\Client\Model\DeleteEmailIdentityResponseContent|\AHRDMail\Client\Model\ValidationExceptionResponseContent, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteEmailIdentityWithHttpInfo($id, $subtenant_id = null, string $contentType = self::contentTypes['deleteEmailIdentity'][0])
    {
        $request = $this->deleteEmailIdentityRequest($id, $subtenant_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\AHRDMail\Client\Model\DeleteEmailIdentityResponseContent',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\AHRDMail\Client\Model\ValidationExceptionResponseContent',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\AHRDMail\Client\Model\DeleteEmailIdentityResponseContent',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AHRDMail\Client\Model\DeleteEmailIdentityResponseContent',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AHRDMail\Client\Model\ValidationExceptionResponseContent',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation deleteEmailIdentityAsync
     *
     * @param  string $id (required)
     * @param  string|null $subtenant_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteEmailIdentity'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteEmailIdentityAsync($id, $subtenant_id = null, string $contentType = self::contentTypes['deleteEmailIdentity'][0])
    {
        return $this->deleteEmailIdentityAsyncWithHttpInfo($id, $subtenant_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteEmailIdentityAsyncWithHttpInfo
     *
     * @param  string $id (required)
     * @param  string|null $subtenant_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteEmailIdentity'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteEmailIdentityAsyncWithHttpInfo($id, $subtenant_id = null, string $contentType = self::contentTypes['deleteEmailIdentity'][0])
    {
        $returnType = '\AHRDMail\Client\Model\DeleteEmailIdentityResponseContent';
        $request = $this->deleteEmailIdentityRequest($id, $subtenant_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteEmailIdentity'
     *
     * @param  string $id (required)
     * @param  string|null $subtenant_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteEmailIdentity'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteEmailIdentityRequest($id, $subtenant_id = null, string $contentType = self::contentTypes['deleteEmailIdentity'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling deleteEmailIdentity'
            );
        }



        $resourcePath = '/email-identity';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $id,
            'id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $subtenant_id,
            'subtenantId', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listCampaignMetrics
     *
     * @param  string $subtenant_id subtenant_id (required)
     * @param  string|null $next_token next_token (optional)
     * @param  float|null $page_size page_size (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listCampaignMetrics'] to see the possible values for this operation
     *
     * @throws \AHRDMail\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \AHRDMail\Client\Model\ListCampaignMetricsResponseContent|\AHRDMail\Client\Model\ValidationExceptionResponseContent
     */
    public function listCampaignMetrics($subtenant_id, $next_token = null, $page_size = null, string $contentType = self::contentTypes['listCampaignMetrics'][0])
    {
        list($response) = $this->listCampaignMetricsWithHttpInfo($subtenant_id, $next_token, $page_size, $contentType);
        return $response;
    }

    /**
     * Operation listCampaignMetricsWithHttpInfo
     *
     * @param  string $subtenant_id (required)
     * @param  string|null $next_token (optional)
     * @param  float|null $page_size (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listCampaignMetrics'] to see the possible values for this operation
     *
     * @throws \AHRDMail\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \AHRDMail\Client\Model\ListCampaignMetricsResponseContent|\AHRDMail\Client\Model\ValidationExceptionResponseContent, HTTP status code, HTTP response headers (array of strings)
     */
    public function listCampaignMetricsWithHttpInfo($subtenant_id, $next_token = null, $page_size = null, string $contentType = self::contentTypes['listCampaignMetrics'][0])
    {
        $request = $this->listCampaignMetricsRequest($subtenant_id, $next_token, $page_size, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\AHRDMail\Client\Model\ListCampaignMetricsResponseContent',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\AHRDMail\Client\Model\ValidationExceptionResponseContent',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\AHRDMail\Client\Model\ListCampaignMetricsResponseContent',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AHRDMail\Client\Model\ListCampaignMetricsResponseContent',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AHRDMail\Client\Model\ValidationExceptionResponseContent',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listCampaignMetricsAsync
     *
     * @param  string $subtenant_id (required)
     * @param  string|null $next_token (optional)
     * @param  float|null $page_size (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listCampaignMetrics'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listCampaignMetricsAsync($subtenant_id, $next_token = null, $page_size = null, string $contentType = self::contentTypes['listCampaignMetrics'][0])
    {
        return $this->listCampaignMetricsAsyncWithHttpInfo($subtenant_id, $next_token, $page_size, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listCampaignMetricsAsyncWithHttpInfo
     *
     * @param  string $subtenant_id (required)
     * @param  string|null $next_token (optional)
     * @param  float|null $page_size (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listCampaignMetrics'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listCampaignMetricsAsyncWithHttpInfo($subtenant_id, $next_token = null, $page_size = null, string $contentType = self::contentTypes['listCampaignMetrics'][0])
    {
        $returnType = '\AHRDMail\Client\Model\ListCampaignMetricsResponseContent';
        $request = $this->listCampaignMetricsRequest($subtenant_id, $next_token, $page_size, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listCampaignMetrics'
     *
     * @param  string $subtenant_id (required)
     * @param  string|null $next_token (optional)
     * @param  float|null $page_size (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listCampaignMetrics'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listCampaignMetricsRequest($subtenant_id, $next_token = null, $page_size = null, string $contentType = self::contentTypes['listCampaignMetrics'][0])
    {

        // verify the required parameter 'subtenant_id' is set
        if ($subtenant_id === null || (is_array($subtenant_id) && count($subtenant_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $subtenant_id when calling listCampaignMetrics'
            );
        }




        $resourcePath = '/metrics/campaigns';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $subtenant_id,
            'subtenantId', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $next_token,
            'nextToken', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_size,
            'pageSize', // param base name
            'number', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listEmailIdentities
     *
     * @param  string $subtenant_id subtenant_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listEmailIdentities'] to see the possible values for this operation
     *
     * @throws \AHRDMail\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \AHRDMail\Client\Model\ListEmailIdentitiesResponseContent|\AHRDMail\Client\Model\ValidationExceptionResponseContent
     */
    public function listEmailIdentities($subtenant_id, string $contentType = self::contentTypes['listEmailIdentities'][0])
    {
        list($response) = $this->listEmailIdentitiesWithHttpInfo($subtenant_id, $contentType);
        return $response;
    }

    /**
     * Operation listEmailIdentitiesWithHttpInfo
     *
     * @param  string $subtenant_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listEmailIdentities'] to see the possible values for this operation
     *
     * @throws \AHRDMail\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \AHRDMail\Client\Model\ListEmailIdentitiesResponseContent|\AHRDMail\Client\Model\ValidationExceptionResponseContent, HTTP status code, HTTP response headers (array of strings)
     */
    public function listEmailIdentitiesWithHttpInfo($subtenant_id, string $contentType = self::contentTypes['listEmailIdentities'][0])
    {
        $request = $this->listEmailIdentitiesRequest($subtenant_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\AHRDMail\Client\Model\ListEmailIdentitiesResponseContent',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\AHRDMail\Client\Model\ValidationExceptionResponseContent',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\AHRDMail\Client\Model\ListEmailIdentitiesResponseContent',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AHRDMail\Client\Model\ListEmailIdentitiesResponseContent',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AHRDMail\Client\Model\ValidationExceptionResponseContent',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listEmailIdentitiesAsync
     *
     * @param  string $subtenant_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listEmailIdentities'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listEmailIdentitiesAsync($subtenant_id, string $contentType = self::contentTypes['listEmailIdentities'][0])
    {
        return $this->listEmailIdentitiesAsyncWithHttpInfo($subtenant_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listEmailIdentitiesAsyncWithHttpInfo
     *
     * @param  string $subtenant_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listEmailIdentities'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listEmailIdentitiesAsyncWithHttpInfo($subtenant_id, string $contentType = self::contentTypes['listEmailIdentities'][0])
    {
        $returnType = '\AHRDMail\Client\Model\ListEmailIdentitiesResponseContent';
        $request = $this->listEmailIdentitiesRequest($subtenant_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listEmailIdentities'
     *
     * @param  string $subtenant_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listEmailIdentities'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listEmailIdentitiesRequest($subtenant_id, string $contentType = self::contentTypes['listEmailIdentities'][0])
    {

        // verify the required parameter 'subtenant_id' is set
        if ($subtenant_id === null || (is_array($subtenant_id) && count($subtenant_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $subtenant_id when calling listEmailIdentities'
            );
        }


        $resourcePath = '/email-identities';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $subtenant_id,
            'subtenantId', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listSubtenantMetrics
     *
     * @param  string|null $next_token next_token (optional)
     * @param  float|null $page_size page_size (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listSubtenantMetrics'] to see the possible values for this operation
     *
     * @throws \AHRDMail\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \AHRDMail\Client\Model\ListSubtenantMetricsResponseContent|\AHRDMail\Client\Model\ValidationExceptionResponseContent
     */
    public function listSubtenantMetrics($next_token = null, $page_size = null, string $contentType = self::contentTypes['listSubtenantMetrics'][0])
    {
        list($response) = $this->listSubtenantMetricsWithHttpInfo($next_token, $page_size, $contentType);
        return $response;
    }

    /**
     * Operation listSubtenantMetricsWithHttpInfo
     *
     * @param  string|null $next_token (optional)
     * @param  float|null $page_size (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listSubtenantMetrics'] to see the possible values for this operation
     *
     * @throws \AHRDMail\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \AHRDMail\Client\Model\ListSubtenantMetricsResponseContent|\AHRDMail\Client\Model\ValidationExceptionResponseContent, HTTP status code, HTTP response headers (array of strings)
     */
    public function listSubtenantMetricsWithHttpInfo($next_token = null, $page_size = null, string $contentType = self::contentTypes['listSubtenantMetrics'][0])
    {
        $request = $this->listSubtenantMetricsRequest($next_token, $page_size, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\AHRDMail\Client\Model\ListSubtenantMetricsResponseContent',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\AHRDMail\Client\Model\ValidationExceptionResponseContent',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\AHRDMail\Client\Model\ListSubtenantMetricsResponseContent',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AHRDMail\Client\Model\ListSubtenantMetricsResponseContent',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AHRDMail\Client\Model\ValidationExceptionResponseContent',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listSubtenantMetricsAsync
     *
     * @param  string|null $next_token (optional)
     * @param  float|null $page_size (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listSubtenantMetrics'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listSubtenantMetricsAsync($next_token = null, $page_size = null, string $contentType = self::contentTypes['listSubtenantMetrics'][0])
    {
        return $this->listSubtenantMetricsAsyncWithHttpInfo($next_token, $page_size, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listSubtenantMetricsAsyncWithHttpInfo
     *
     * @param  string|null $next_token (optional)
     * @param  float|null $page_size (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listSubtenantMetrics'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listSubtenantMetricsAsyncWithHttpInfo($next_token = null, $page_size = null, string $contentType = self::contentTypes['listSubtenantMetrics'][0])
    {
        $returnType = '\AHRDMail\Client\Model\ListSubtenantMetricsResponseContent';
        $request = $this->listSubtenantMetricsRequest($next_token, $page_size, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listSubtenantMetrics'
     *
     * @param  string|null $next_token (optional)
     * @param  float|null $page_size (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listSubtenantMetrics'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listSubtenantMetricsRequest($next_token = null, $page_size = null, string $contentType = self::contentTypes['listSubtenantMetrics'][0])
    {




        $resourcePath = '/metrics/subtenants';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $next_token,
            'nextToken', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_size,
            'pageSize', // param base name
            'number', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation sendEmail
     *
     * @param  \AHRDMail\Client\Model\SendEmailRequestContent $send_email_request_content send_email_request_content (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendEmail'] to see the possible values for this operation
     *
     * @throws \AHRDMail\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \AHRDMail\Client\Model\SendEmailResponseContent|\AHRDMail\Client\Model\ValidationExceptionResponseContent
     */
    public function sendEmail($send_email_request_content, string $contentType = self::contentTypes['sendEmail'][0])
    {
        list($response) = $this->sendEmailWithHttpInfo($send_email_request_content, $contentType);
        return $response;
    }

    /**
     * Operation sendEmailWithHttpInfo
     *
     * @param  \AHRDMail\Client\Model\SendEmailRequestContent $send_email_request_content (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendEmail'] to see the possible values for this operation
     *
     * @throws \AHRDMail\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \AHRDMail\Client\Model\SendEmailResponseContent|\AHRDMail\Client\Model\ValidationExceptionResponseContent, HTTP status code, HTTP response headers (array of strings)
     */
    public function sendEmailWithHttpInfo($send_email_request_content, string $contentType = self::contentTypes['sendEmail'][0])
    {
        $request = $this->sendEmailRequest($send_email_request_content, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\AHRDMail\Client\Model\SendEmailResponseContent',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\AHRDMail\Client\Model\ValidationExceptionResponseContent',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\AHRDMail\Client\Model\SendEmailResponseContent',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AHRDMail\Client\Model\SendEmailResponseContent',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AHRDMail\Client\Model\ValidationExceptionResponseContent',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation sendEmailAsync
     *
     * @param  \AHRDMail\Client\Model\SendEmailRequestContent $send_email_request_content (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendEmail'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendEmailAsync($send_email_request_content, string $contentType = self::contentTypes['sendEmail'][0])
    {
        return $this->sendEmailAsyncWithHttpInfo($send_email_request_content, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sendEmailAsyncWithHttpInfo
     *
     * @param  \AHRDMail\Client\Model\SendEmailRequestContent $send_email_request_content (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendEmail'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendEmailAsyncWithHttpInfo($send_email_request_content, string $contentType = self::contentTypes['sendEmail'][0])
    {
        $returnType = '\AHRDMail\Client\Model\SendEmailResponseContent';
        $request = $this->sendEmailRequest($send_email_request_content, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'sendEmail'
     *
     * @param  \AHRDMail\Client\Model\SendEmailRequestContent $send_email_request_content (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendEmail'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function sendEmailRequest($send_email_request_content, string $contentType = self::contentTypes['sendEmail'][0])
    {

        // verify the required parameter 'send_email_request_content' is set
        if ($send_email_request_content === null || (is_array($send_email_request_content) && count($send_email_request_content) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $send_email_request_content when calling sendEmail'
            );
        }


        $resourcePath = '/email';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($send_email_request_content)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($send_email_request_content));
            } else {
                $httpBody = $send_email_request_content;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
