<?php
/**
 * AhrdMailDnsRecordName
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  AHRDMail\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AppService
 *
 * description_placeholder
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AHRDMail\Client\Model;
use \AHRDMail\Client\ObjectSerializer;

/**
 * AhrdMailDnsRecordName Class Doc Comment
 *
 * @category Class
 * @package  AHRDMail\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AhrdMailDnsRecordName
{
    /**
     * Possible values of this enum
     */
    public const AT = '@';

    public const DMARC = '_dmarc';

    public const MAIL = 'mail';

    public const DKIM2048_1__DOMAINKEY = 'dkim2048_1._domainkey';

    public const LINKS = 'links';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::AT,
            self::DMARC,
            self::MAIL,
            self::DKIM2048_1__DOMAINKEY,
            self::LINKS
        ];
    }
}


