<?php
/**
 * CreateEmailIdentityResponseContent
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  AHRDMail\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AppService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AHRDMail\Client\Model;

use \ArrayAccess;
use \AHRDMail\Client\ObjectSerializer;

/**
 * CreateEmailIdentityResponseContent Class Doc Comment
 *
 * @category Class
 * @package  AHRDMail\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CreateEmailIdentityResponseContent implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CreateEmailIdentityResponseContent';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'identity_arn' => 'string',
        'dkim_records' => '\AHRDMail\Client\Model\DkimSettings',
        'verification_records' => '\AHRDMail\Client\Model\VerificationTokens',
        'status' => '\AHRDMail\Client\Model\EmailIdentityStatus',
        'dns_records' => '\AHRDMail\Client\Model\DnsRecord[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'identity_arn' => null,
        'dkim_records' => null,
        'verification_records' => null,
        'status' => null,
        'dns_records' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'identity_arn' => false,
        'dkim_records' => false,
        'verification_records' => false,
        'status' => false,
        'dns_records' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'identity_arn' => 'identityArn',
        'dkim_records' => 'dkimRecords',
        'verification_records' => 'verificationRecords',
        'status' => 'status',
        'dns_records' => 'dnsRecords'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'identity_arn' => 'setIdentityArn',
        'dkim_records' => 'setDkimRecords',
        'verification_records' => 'setVerificationRecords',
        'status' => 'setStatus',
        'dns_records' => 'setDnsRecords'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'identity_arn' => 'getIdentityArn',
        'dkim_records' => 'getDkimRecords',
        'verification_records' => 'getVerificationRecords',
        'status' => 'getStatus',
        'dns_records' => 'getDnsRecords'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('identity_arn', $data ?? [], null);
        $this->setIfExists('dkim_records', $data ?? [], null);
        $this->setIfExists('verification_records', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('dns_records', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets identity_arn
     *
     * @return string|null
     */
    public function getIdentityArn()
    {
        return $this->container['identity_arn'];
    }

    /**
     * Sets identity_arn
     *
     * @param string|null $identity_arn identity_arn
     *
     * @return self
     */
    public function setIdentityArn($identity_arn)
    {
        if (is_null($identity_arn)) {
            throw new \InvalidArgumentException('non-nullable identity_arn cannot be null');
        }
        $this->container['identity_arn'] = $identity_arn;

        return $this;
    }

    /**
     * Gets dkim_records
     *
     * @return \AHRDMail\Client\Model\DkimSettings|null
     */
    public function getDkimRecords()
    {
        return $this->container['dkim_records'];
    }

    /**
     * Sets dkim_records
     *
     * @param \AHRDMail\Client\Model\DkimSettings|null $dkim_records dkim_records
     *
     * @return self
     */
    public function setDkimRecords($dkim_records)
    {
        if (is_null($dkim_records)) {
            throw new \InvalidArgumentException('non-nullable dkim_records cannot be null');
        }
        $this->container['dkim_records'] = $dkim_records;

        return $this;
    }

    /**
     * Gets verification_records
     *
     * @return \AHRDMail\Client\Model\VerificationTokens|null
     */
    public function getVerificationRecords()
    {
        return $this->container['verification_records'];
    }

    /**
     * Sets verification_records
     *
     * @param \AHRDMail\Client\Model\VerificationTokens|null $verification_records verification_records
     *
     * @return self
     */
    public function setVerificationRecords($verification_records)
    {
        if (is_null($verification_records)) {
            throw new \InvalidArgumentException('non-nullable verification_records cannot be null');
        }
        $this->container['verification_records'] = $verification_records;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \AHRDMail\Client\Model\EmailIdentityStatus|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \AHRDMail\Client\Model\EmailIdentityStatus|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets dns_records
     *
     * @return \AHRDMail\Client\Model\DnsRecord[]|null
     */
    public function getDnsRecords()
    {
        return $this->container['dns_records'];
    }

    /**
     * Sets dns_records
     *
     * @param \AHRDMail\Client\Model\DnsRecord[]|null $dns_records dns_records
     *
     * @return self
     */
    public function setDnsRecords($dns_records)
    {
        if (is_null($dns_records)) {
            throw new \InvalidArgumentException('non-nullable dns_records cannot be null');
        }
        $this->container['dns_records'] = $dns_records;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


