<?php
/**
 * CreateMailboxRequestContent
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Ahrdmail\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AppService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Ahrdmail\Client\Model;

use \ArrayAccess;
use \Ahrdmail\Client\ObjectSerializer;

/**
 * CreateMailboxRequestContent Class Doc Comment
 *
 * @category Class
 * @package  Ahrdmail\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CreateMailboxRequestContent implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CreateMailboxRequestContent';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'subtenant_id' => 'string',
        'domain' => 'string',
        'mailbox_name' => 'string',
        'webhook_url' => 'string',
        'signing_secrets' => 'array<string,\Ahrdmail\Client\Model\InboundEmailSigningSecret>'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'subtenant_id' => null,
        'domain' => null,
        'mailbox_name' => null,
        'webhook_url' => null,
        'signing_secrets' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'subtenant_id' => false,
        'domain' => false,
        'mailbox_name' => false,
        'webhook_url' => false,
        'signing_secrets' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'subtenant_id' => 'subtenantId',
        'domain' => 'domain',
        'mailbox_name' => 'mailboxName',
        'webhook_url' => 'webhookUrl',
        'signing_secrets' => 'signingSecrets'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'subtenant_id' => 'setSubtenantId',
        'domain' => 'setDomain',
        'mailbox_name' => 'setMailboxName',
        'webhook_url' => 'setWebhookUrl',
        'signing_secrets' => 'setSigningSecrets'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'subtenant_id' => 'getSubtenantId',
        'domain' => 'getDomain',
        'mailbox_name' => 'getMailboxName',
        'webhook_url' => 'getWebhookUrl',
        'signing_secrets' => 'getSigningSecrets'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('subtenant_id', $data ?? [], null);
        $this->setIfExists('domain', $data ?? [], null);
        $this->setIfExists('mailbox_name', $data ?? [], null);
        $this->setIfExists('webhook_url', $data ?? [], null);
        $this->setIfExists('signing_secrets', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['subtenant_id'] === null) {
            $invalidProperties[] = "'subtenant_id' can't be null";
        }
        if ((mb_strlen($this->container['subtenant_id']) > 64)) {
            $invalidProperties[] = "invalid value for 'subtenant_id', the character length must be smaller than or equal to 64.";
        }

        if ((mb_strlen($this->container['subtenant_id']) < 1)) {
            $invalidProperties[] = "invalid value for 'subtenant_id', the character length must be bigger than or equal to 1.";
        }

        if (!preg_match("/^[a-zA-Z0-9]+$/", $this->container['subtenant_id'])) {
            $invalidProperties[] = "invalid value for 'subtenant_id', must be conform to the pattern /^[a-zA-Z0-9]+$/.";
        }

        if ($this->container['domain'] === null) {
            $invalidProperties[] = "'domain' can't be null";
        }
        if ($this->container['mailbox_name'] === null) {
            $invalidProperties[] = "'mailbox_name' can't be null";
        }
        if ((mb_strlen($this->container['mailbox_name']) > 64)) {
            $invalidProperties[] = "invalid value for 'mailbox_name', the character length must be smaller than or equal to 64.";
        }

        if ((mb_strlen($this->container['mailbox_name']) < 1)) {
            $invalidProperties[] = "invalid value for 'mailbox_name', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['webhook_url'] === null) {
            $invalidProperties[] = "'webhook_url' can't be null";
        }
        if ((mb_strlen($this->container['webhook_url']) > 2048)) {
            $invalidProperties[] = "invalid value for 'webhook_url', the character length must be smaller than or equal to 2048.";
        }

        if ((mb_strlen($this->container['webhook_url']) < 8)) {
            $invalidProperties[] = "invalid value for 'webhook_url', the character length must be bigger than or equal to 8.";
        }

        if (!preg_match("/^https:\/\/[^\\s]+$/", $this->container['webhook_url'])) {
            $invalidProperties[] = "invalid value for 'webhook_url', must be conform to the pattern /^https:\/\/[^\\s]+$/.";
        }

        if ($this->container['signing_secrets'] === null) {
            $invalidProperties[] = "'signing_secrets' can't be null";
        }
        if ((count($this->container['signing_secrets']) > 2)) {
            $invalidProperties[] = "invalid value for 'signing_secrets', number of items must be less than or equal to 2.";
        }

        if ((count($this->container['signing_secrets']) < 1)) {
            $invalidProperties[] = "invalid value for 'signing_secrets', number of items must be greater than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets subtenant_id
     *
     * @return string
     */
    public function getSubtenantId()
    {
        return $this->container['subtenant_id'];
    }

    /**
     * Sets subtenant_id
     *
     * @param string $subtenant_id subtenant_id
     *
     * @return self
     */
    public function setSubtenantId($subtenant_id)
    {
        if (is_null($subtenant_id)) {
            throw new \InvalidArgumentException('non-nullable subtenant_id cannot be null');
        }
        if ((mb_strlen($subtenant_id) > 64)) {
            throw new \InvalidArgumentException('invalid length for $subtenant_id when calling CreateMailboxRequestContent., must be smaller than or equal to 64.');
        }
        if ((mb_strlen($subtenant_id) < 1)) {
            throw new \InvalidArgumentException('invalid length for $subtenant_id when calling CreateMailboxRequestContent., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^[a-zA-Z0-9]+$/", ObjectSerializer::toString($subtenant_id)))) {
            throw new \InvalidArgumentException("invalid value for \$subtenant_id when calling CreateMailboxRequestContent., must conform to the pattern /^[a-zA-Z0-9]+$/.");
        }

        $this->container['subtenant_id'] = $subtenant_id;

        return $this;
    }

    /**
     * Gets domain
     *
     * @return string
     */
    public function getDomain()
    {
        return $this->container['domain'];
    }

    /**
     * Sets domain
     *
     * @param string $domain domain
     *
     * @return self
     */
    public function setDomain($domain)
    {
        if (is_null($domain)) {
            throw new \InvalidArgumentException('non-nullable domain cannot be null');
        }
        $this->container['domain'] = $domain;

        return $this;
    }

    /**
     * Gets mailbox_name
     *
     * @return string
     */
    public function getMailboxName()
    {
        return $this->container['mailbox_name'];
    }

    /**
     * Sets mailbox_name
     *
     * @param string $mailbox_name mailbox_name
     *
     * @return self
     */
    public function setMailboxName($mailbox_name)
    {
        if (is_null($mailbox_name)) {
            throw new \InvalidArgumentException('non-nullable mailbox_name cannot be null');
        }
        if ((mb_strlen($mailbox_name) > 64)) {
            throw new \InvalidArgumentException('invalid length for $mailbox_name when calling CreateMailboxRequestContent., must be smaller than or equal to 64.');
        }
        if ((mb_strlen($mailbox_name) < 1)) {
            throw new \InvalidArgumentException('invalid length for $mailbox_name when calling CreateMailboxRequestContent., must be bigger than or equal to 1.');
        }

        $this->container['mailbox_name'] = $mailbox_name;

        return $this;
    }

    /**
     * Gets webhook_url
     *
     * @return string
     */
    public function getWebhookUrl()
    {
        return $this->container['webhook_url'];
    }

    /**
     * Sets webhook_url
     *
     * @param string $webhook_url webhook_url
     *
     * @return self
     */
    public function setWebhookUrl($webhook_url)
    {
        if (is_null($webhook_url)) {
            throw new \InvalidArgumentException('non-nullable webhook_url cannot be null');
        }
        if ((mb_strlen($webhook_url) > 2048)) {
            throw new \InvalidArgumentException('invalid length for $webhook_url when calling CreateMailboxRequestContent., must be smaller than or equal to 2048.');
        }
        if ((mb_strlen($webhook_url) < 8)) {
            throw new \InvalidArgumentException('invalid length for $webhook_url when calling CreateMailboxRequestContent., must be bigger than or equal to 8.');
        }
        if ((!preg_match("/^https:\/\/[^\\s]+$/", ObjectSerializer::toString($webhook_url)))) {
            throw new \InvalidArgumentException("invalid value for \$webhook_url when calling CreateMailboxRequestContent., must conform to the pattern /^https:\/\/[^\\s]+$/.");
        }

        $this->container['webhook_url'] = $webhook_url;

        return $this;
    }

    /**
     * Gets signing_secrets
     *
     * @return array<string,\Ahrdmail\Client\Model\InboundEmailSigningSecret>
     */
    public function getSigningSecrets()
    {
        return $this->container['signing_secrets'];
    }

    /**
     * Sets signing_secrets
     *
     * @param array<string,\Ahrdmail\Client\Model\InboundEmailSigningSecret> $signing_secrets signing_secrets
     *
     * @return self
     */
    public function setSigningSecrets($signing_secrets)
    {
        if (is_null($signing_secrets)) {
            throw new \InvalidArgumentException('non-nullable signing_secrets cannot be null');
        }

        if ((count($signing_secrets) > 2)) {
            throw new \InvalidArgumentException('invalid value for $signing_secrets when calling CreateMailboxRequestContent., number of items must be less than or equal to 2.');
        }
        if ((count($signing_secrets) < 1)) {
            throw new \InvalidArgumentException('invalid length for $signing_secrets when calling CreateMailboxRequestContent., number of items must be greater than or equal to 1.');
        }
        $this->container['signing_secrets'] = $signing_secrets;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


