<?php
/**
 * EmailIdentityStatus
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  AHRDMail\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AppService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AHRDMail\Client\Model;
use \AHRDMail\Client\ObjectSerializer;

/**
 * EmailIdentityStatus Class Doc Comment
 *
 * @category Class
 * @package  AHRDMail\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EmailIdentityStatus
{
    /**
     * Possible values of this enum
     */
    public const PENDING_VERIFICATION = 'PENDING_VERIFICATION';

    public const VERIFIED = 'VERIFIED';

    public const FAILED = 'FAILED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PENDING_VERIFICATION,
            self::VERIFIED,
            self::FAILED
        ];
    }
}


