<?php
/**
 * MailboxStatus
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Ahrdmail\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AppService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Ahrdmail\Client\Model;
use \Ahrdmail\Client\ObjectSerializer;

/**
 * MailboxStatus Class Doc Comment
 *
 * @category Class
 * @package  Ahrdmail\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MailboxStatus
{
    /**
     * Possible values of this enum
     */
    public const ACTIVE = 'ACTIVE';

    public const INACTIVE = 'INACTIVE';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ACTIVE,
            self::INACTIVE
        ];
    }
}


