<?php
/**
 * SubtenantMetricsSummaryTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  AHRDMail\client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AppService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace AHRDMail\client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * SubtenantMetricsSummaryTest Class Doc Comment
 *
 * @category    Class
 * @description SubtenantMetricsSummary
 * @package     AHRDMail\client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SubtenantMetricsSummaryTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SubtenantMetricsSummary"
     */
    public function testSubtenantMetricsSummary()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tenant_id"
     */
    public function testPropertyTenantId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "subtenant_id"
     */
    public function testPropertySubtenantId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "clicks"
     */
    public function testPropertyClicks()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "opens"
     */
    public function testPropertyOpens()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "complains"
     */
    public function testPropertyComplains()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bounces"
     */
    public function testPropertyBounces()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
